"""Storage port interfaces."""
from abc import ABC, abstractmethod
from typing import Optional


class ScoutStoragePort(ABC):
    @abstractmethod
    async def create_scout(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def get_scout(self, user_id: str, scout_name: str) -> dict | None: ...
    @abstractmethod
    async def get_scout_by_id(self, scout_id: str) -> dict | None: ...
    @abstractmethod
    async def list_scouts(self, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def delete_scout(self, user_id: str, scout_name: str) -> None: ...
    @abstractmethod
    async def update_scout(self, user_id: str, scout_name: str, updates: dict) -> dict | None: ...
    @abstractmethod
    async def deactivate_scout(self, scout_id: str) -> None: ...


class ExecutionStoragePort(ABC):
    @abstractmethod
    async def store_execution(self, user_id: str, scout_name: str, scout_type: str,
                              summary_text: str, is_duplicate: bool, started_at: str,
                              embedding: list[float] | None = None,
                              content_hash: str | None = None,
                              provider: str | None = None) -> dict: ...
    @abstractmethod
    async def get_recent_executions(self, user_id: str, scout_id: str,
                                     limit: int = 5) -> list[dict]: ...
    @abstractmethod
    async def get_recent_embeddings(self, user_id: str, scout_name: str, limit: int = 20) -> list[dict]: ...
    @abstractmethod
    async def get_latest_content_hash(self, user_id: str, scout_id: str) -> str | None: ...
    @abstractmethod
    async def delete_executions_for_scout(self, user_id: str, scout_name: str) -> None: ...


class RunStoragePort(ABC):
    @abstractmethod
    async def store_run(self, scout_id: str, user_id: str, status: str,
                        error_message: str = None, **kwargs) -> dict: ...
    @abstractmethod
    async def get_latest_runs(self, user_id: str, limit: int = 10) -> list[dict]: ...
    @abstractmethod
    async def get_latest_run_for_scout(self, scout_id: str) -> dict | None: ...
    @abstractmethod
    async def delete_runs_for_scout(self, user_id: str, scout_name: str) -> None: ...


class PostSnapshotStoragePort(ABC):
    @abstractmethod
    async def store_snapshot(self, user_id: str, scout_id: str,
                              platform: str, handle: str, posts: list[dict]) -> None: ...
    @abstractmethod
    async def get_snapshot(self, user_id: str, scout_id: str) -> list[dict]: ...
    @abstractmethod
    async def delete_snapshot(self, user_id: str, scout_name: str) -> None: ...


class UnitStoragePort(ABC):
    @abstractmethod
    async def store_units(self, user_id: str, scout_id: str, units: list[dict]) -> None: ...
    @abstractmethod
    async def search_units(self, user_id: str, query_embedding: list[float],
                            filters: dict = None, limit: int = 20) -> list[dict]: ...
    @abstractmethod
    async def get_units_for_article(self, article_id: str) -> list[dict]: ...
    @abstractmethod
    async def get_units_by_location(self, user_id: str, country: str,
                                     state: str = None, city: str = None,
                                     limit: int = 50) -> list[dict]: ...
    @abstractmethod
    async def get_units_by_topic(self, user_id: str, topic: str,
                                  limit: int = 50) -> list[dict]: ...
    @abstractmethod
    async def get_distinct_locations(self, user_id: str) -> list[dict]: ...
    @abstractmethod
    async def get_distinct_topics(self, user_id: str) -> list[str]: ...
    @abstractmethod
    async def mark_used(self, unit_ids: list[str]) -> None: ...
    @abstractmethod
    async def get_all_unused_units(self, user_id: str, limit: int = 50) -> list[dict]: ...
    @abstractmethod
    async def get_units_by_scout(self, user_id: str, scout_id: str, limit: int = 50) -> list[dict]: ...


class SeenRecordStoragePort(ABC):
    @abstractmethod
    async def mark_seen(self, scout_id: str, user_id: str, signature: str) -> bool: ...
    @abstractmethod
    async def is_seen(self, scout_id: str, user_id: str, signature: str) -> bool: ...
    @abstractmethod
    async def delete_seen_records(self, user_id: str, scout_name: str) -> None: ...


class UserStoragePort(ABC):
    @abstractmethod
    async def get_user(self, user_id: str) -> dict | None: ...
    @abstractmethod
    async def create_or_update_user(self, user_id: str, data: dict) -> dict: ...
    @abstractmethod
    async def update_profile(self, user_id: str, updates: dict) -> None: ...
    @abstractmethod
    async def get_cms_config(self, user_id: str) -> dict: ...
    @abstractmethod
    async def get_balance(self, user_id: str) -> int: ...
    @abstractmethod
    async def create_credits(self, user_id: str, monthly_cap: int, tier: str,
                             update_on: str | None = None) -> None: ...
    @abstractmethod
    async def update_credits(self, user_id: str, updates: dict) -> None: ...
    @abstractmethod
    async def decrement_credits(self, user_id: str, amount: int) -> bool: ...
    @abstractmethod
    async def create_org(self, org_id: str, monthly_cap: int,
                         update_on: str | None, org_name: str) -> None: ...
    @abstractmethod
    async def get_org_credits(self, org_id: str) -> dict | None: ...
    @abstractmethod
    async def get_org_balance(self, org_id: str) -> int: ...
    @abstractmethod
    async def decrement_org_credits(self, org_id: str, amount: int) -> bool: ...
    @abstractmethod
    async def update_org_credits(self, org_id: str, new_cap: int, new_update_on: str) -> None: ...
    @abstractmethod
    async def claim_seat(self, org_id: str, user_id: str, tier_before_team: str) -> bool: ...
    @abstractmethod
    async def cancel_team_org(self, org_id: str) -> None: ...


class PromiseStoragePort(ABC):
    @abstractmethod
    async def store_promises(self, user_id: str, scraper_name: str, promises: list) -> None: ...
    @abstractmethod
    async def mark_promises_notified(self, user_id: str, scraper_name: str,
                                      promise_ids: list[str]) -> None: ...
    @abstractmethod
    async def get_stored_hash(self, user_id: str, scraper_name: str) -> str: ...
    @abstractmethod
    async def get_processed_urls(self, user_id: str, scraper_name: str) -> list[str]: ...
    @abstractmethod
    async def update_scraper_record(self, user_id: str, scraper_name: str,
                                     content_hash: str, new_processed: list[str]) -> None: ...
    @abstractmethod
    async def delete_promises_for_scout(self, user_id: str, scout_name: str) -> None: ...
